import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LogosService {
  ruta_partidos = './assets/logos/partidos/';
  ruta_coaliciones = './assets/logos/coaliciones/';
  constructor() {}

  partidos = [
    {
      imagen: this.ruta_partidos + 'pan.png',
      clase: 1,
      id: 1,
      nombre: 'Partido Acción Nacional',
      acronimo: 'PAN',
      color: '#C0392B',
    },
    {
      imagen: this.ruta_partidos + 'PRI.png',
      clase: 1,
      id: 2,
      nombre: 'Partido Revolucionario Institucional',
      acronimo: 'PRI',
      color: '#E74C3C',
    },
    {
      imagen: this.ruta_partidos + 'prd.png',
      clase: 1,
      id: 3,
      nombre: 'Partido de la Revolucion Democratica',
      acronimo: 'PRD',
      color: '#9B59B6',
    },
    {
      imagen: this.ruta_partidos + 'PT.png',
      clase: 1,
      id: 4,
      nombre: 'Partido del Trabajo',
      acronimo: 'PT',
      color: '#8E44AD',
    },
    {
      imagen: this.ruta_partidos + 'pvem.png',
      clase: 1,
      id: 5,
      nombre: 'Partido Verde Ecologista de Mexico',
      acronimo: 'PVEM',
      color: '#2980B9',
    },
    {
      imagen: this.ruta_partidos + 'mc.png',
      clase: 1,
      id: 6,
      nombre: 'Movimiento Ciudadano',
      acronimo: 'MC',
      color: '#3498DB',
    },
    {
      imagen: this.ruta_partidos + 'MORENA.png',
      clase: 1,
      id: 7,
      nombre: 'Morena',
      acronimo: 'MORENA',
      color: '#1ABC9C',
    },
    {
      imagen: this.ruta_partidos + 'naz.png',
      clase: 1,
      id: 11,
      nombre: 'Nueva Alianza Zacatecas',
      acronimo: 'NAZ',
      color: '#16A085',
    },
    {
      imagen: this.ruta_partidos + 'PAZ.jpg',
      clase: 1,
      id: 12,
      nombre: 'Para Desarrollar Zacatecas',
      acronimo: 'PAZ',
      color: '#27AE60',
    },
    {
      imagen: this.ruta_partidos + 'mdz.png',
      clase: 1,
      id: 13,
      nombre: 'Movimiento Dignidad Zacatecas A.C.',
      acronimo: 'MDZ',
      color: '#2ECC71',
    },
    {
      imagen: this.ruta_partidos + 'PP.png',
      clase: 1,
      id: 15,
      nombre: 'Partido del Pueblo',
      acronimo: 'PP',
      color: '#F1C40F',
    },
    {
      imagen: this.ruta_partidos + 'fam.png',
      clase: 1,
      id: 14,
      nombre: 'La Familia Primero',
      acronimo: 'FAM',
      color: '#F39C12',
    },
    {
      imagen: this.ruta_partidos + 'PES.png',
      clase: 1,
      id: 8,
      nombre: 'Encuentro Solidario',
      acronimo: 'PES',
      color: '#E67E22',
    },
    {
      imagen: this.ruta_partidos + 'RSP.png',
      clase: 1,
      id: 9,
      nombre: 'Redes Sociales Progresistas',
      acronimo: 'RSP',
      color: '#D35400',
    },
    {
      imagen: this.ruta_partidos + 'fsm.png',
      clase: 1,
      id: 10,
      nombre: 'Fuerza Social por México',
      acronimo: 'FSM',
      color: '#BDC3C7',
    },
    {
      imagen: this.ruta_partidos + 'cand_ind_1.png',
      clase: 1,
      id: 34,
      nombre: 'Yahir Emmanuel Herrera Flores',
      acronimo: 'CAND_IND_1',
      color: '#95A5A6',
    },
    {
      imagen: this.ruta_partidos + 'cand_ind_2.png',
      clase: 1,
      id: 35,
      nombre: 'Ma. de Jesus Hernández Alemán',
      acronimo: 'CAND_IND_2',
      color: '#7F8C8D',
    },
    {
      imagen: this.ruta_partidos + 'cand_ind_3.png',
      clase: 1,
      id: 36,
      nombre: 'Román Tarango Rodriguez',
      acronimo: 'CAND_IND_3',
      color: '#34495E',
    },
    {
      imagen: this.ruta_partidos + 'cand_ind_4.png',
      clase: 1,
      id: 37,
      nombre: 'Martina Marín Chávez',
      acronimo: 'CAND_IND_4',
      color: '#E6B0AA',
    },
    // {
    //   imagen: this.ruta_partidos + 'cand_inds.png',
    //   clase: 1,
    //   id: 100,
    //   nombre: 'CANDIDATOS INDEPENDIENTES',
    //   acronimo: 'CI',
    //   color: '#b5e61d',
    // },
  ];

  coalisiones = [
    {
      imagen: this.ruta_coaliciones + 'pan_pri_prd.png',
      clase: 3,
      id: 16,
      nombre: 'Coalición Va por Zacatecas',
      acronimo: 'PAN_PRI_PRD',
      color: '#F5B7B1',
    },
    {
      imagen: this.ruta_coaliciones + 'pan_pri.png',
      clase: 2,
      id: 17,
      nombre: 'Coalición Va por Zacatecas',
      acronimo: 'PAN_PRI',
      color: '#D7BDE2',
    },
    {
      imagen: this.ruta_coaliciones + 'pan_prd.png',
      clase: 2,
      id: 18,
      nombre: 'Coalición Va por Zacatecas',
      acronimo: 'PAN_PRD',
      color: '#D2B4DE',
    },
    {
      imagen: this.ruta_coaliciones + 'pri_prd.png',
      clase: 2,
      id: 19,
      nombre: 'Coalición Va por Zacatecas',
      acronimo: 'PRI_PRD',
      color: '#A9CCE3',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_pvem_morena_naz.png',
      clase: 4,
      id: 20,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_PVEM_MORENA_NAZ',
      color: '#AED6F1',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_pvem_morena.png',
      clase: 3,
      id: 21,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_PVEM_MORENA',
      color: '#A3E4D7',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_pvem_naz.png',
      clase: 3,
      id: 22,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_PVEM_NAZ',
      color: '#A2D9CE',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_morena_naz.png',
      clase: 3,
      id: 23,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_MORENA_NAZ',
      color: '#E59866',
    },
    {
      imagen: this.ruta_coaliciones + 'pvem_morena_naz.png',
      clase: 3,
      id: 24,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PVEM_MORENA_NAZ',
      color: '#641E16',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_pvem.png',
      clase: 2,
      id: 28,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_PVEM',
      color: '#117A65',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_morena.png',
      clase: 2,
      id: 27,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_MORENA',
      color: '#873600',
    },
    {
      imagen: this.ruta_coaliciones + 'pt_naz.png',
      clase: 2,
      id: 29,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PT_NAZ',
      color: '#1A5276',
    },
    {
      imagen: this.ruta_coaliciones + 'pvem_morena.png',
      clase: 2,
      id: 25,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PVEM_MORENA',
      color: '#F6DDCC',
    },
    {
      imagen: this.ruta_coaliciones + 'pvem_naz.png',
      clase: 2,
      id: 30,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'PVEM_NAZ',
      color: '#ABB2B9',
    },
    {
      imagen: this.ruta_coaliciones + 'morena_naz.png',
      clase: 2,
      id: 26,
      nombre: 'Coalición Juntos Haremos Historia',
      acronimo: 'MORENA_NAZ',
      color: 'purple',
    },
  ];

  getFuente(id: number, clase: number) {
    let img;
    if (clase == 1) img = this.partidos.find((i) => i.id == id);
    else img = this.coalisiones.find((i) => i.id == id);
    return img.imagen;
  }
}
